# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fonts @ American Bible Society
email: dpeters@americanbible.org
description: > # this means to ignore newlines until "baseurl:"
  A playground for exploring fonts and typography for American Bible Society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://absfonts.com" # the base hostname & protocol for your site
twitter_username: dallasbpeters
github_username:  dallasbpeters

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude: [node_modules, Gruntfile.js, package.json]

gems:
  - jekyll-redirect-from

navigation:
 - title: Gotham
   url: /gotham/
 - title: Montserrat
   url: /montserrat/
 - title: Charis
   url: /charis/
 - title: Bodoni
   url: /bodoni/
